[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["denglitong <litongdeng@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# 在 Rust 中，代码包被称为 crates
